spring:
  profiles: local
  datasource:
    url: jdbc:h2:~/data/demo
  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:~/data/test
  jpa:
    hibernate:
      ddl-auto: update
